title: "Read-QC Pipeline report"
subtitle: "Quality control of MiSeq runs"
custom_logo: "pipelinelogo.png"
custom_logo_title: "Read-QC - checking sequencing runs."
custom_logo_url: "http://www.github.com/marchoeppner/read-qc"
skip_versions_section: true

extra_fn_clean_exts:
    - _R1
    - _R2
    - _duplicate_metrics.txt
    - .pass

report_comment: >
    This report has been generated automatically by marchoeppner/read-qc.
    For help interpreting the outputs, please see: https://github.com/marchoeppner/read-qc
report_header_info:
    - Contact E-mail: "mphoeppner@gmail.com"
    - Application Type: "QC of sequencing runs"

top_modules:
    - 'general_stats'

report_section_order:
    software_versions:
        order: -1001